export const SERVICE_ADD = 'SERVICE_ADD'
export const SERVICE_REMOVE = 'SERVICE_REMOVE'
export const SERVICE_CLEAR_FIELD = 'SERVICE_CLEAR_FIELD'
export const SERVICE_CHANGE_FIELD = 'SERVICE_CHANGE_FIELD'
